server:
  port: 8082

# Configuration Consul (Desactivee)
# spring:
#   cloud:
#     consul:
#       host: localhost
#       port: 8500
#       discovery:
#         service-name: SERVICE-VOITURE
#         health-check-interval: 10s
#         instance-id: ${spring.application.name}:${server.port}
#         prefer-ip-address: true

# Configuration Eureka (Activee)
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
